version: '3.4'
services:
  health-med-api:
    container_name: health-med-api
    cpus: 2
    mem_limit: 2000m
    environment:
      - NODE_ENV=development
    networks:
      - local-network
    build:
      dockerfile: ./Dockerfile
      context: .
      target: development

    ports:
      - 3001:3001
    volumes:
      - .:/app # to sync code changes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3001/health-check"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  local-network:
    name: local-network
    external: true
